<a href="https://colab.research.google.com/github/mhrznamrit/dsml_batch_12/blob/main/Day26_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# 1D Numpy

arr_1d = np.array([1,2,3,4,5])
print(arr_1d)

[1 2 3 4 5]


In [ ]:
# 1D Numpy

arr_1d = np.array([1,2,3,4,5.5])
print(arr_1d)

[1.  2.  3.  4.  5.5]


In [ ]:
arr_1d.shape

(5,)

In [ ]:
# 2D Numpy

arr_2d = np.array([[1,2,3,4,5], [3,4,5,6,7]])
print(arr_2d)

[[1 2 3 4 5]
 [3 4 5 6 7]]


In [ ]:
arr_2d.shape

(2, 5)

In [ ]:
# 3D Numpy (Nested array)

arr_3d = np.array([[[1,2,3,4,5], [5,6,7,8,9]], [[2,4,6,8,0], [1,3,5,7,9]]])
print(arr_3d)

[[[1 2 3 4 5]
  [5 6 7 8 9]]

 [[2 4 6 8 0]
  [1 3 5 7 9]]]


In [ ]:
arr_3d.shape

(2, 2, 5)

# List vs Numpy array

In [ ]:
#list

import time
start = time.time()
py_list = [i*2 for i in range(100000000)]
print("\n List Operation time: ", time.time()-start)


 List Operation time:  8.033027648925781


In [ ]:
#numpy

start = time.time()
np_array = np.arange(100000000) * 2
print("\nList Operation time: ", time.time()-start)


List Operation time:  0.30403828620910645


In [ ]:
py_list = [1,2,3]
print("Python list multiplication: ", py_list * 3)

Python list multiplication:  [1, 2, 3, 1, 2, 3, 1, 2, 3]


In [ ]:
ny_array = np.array([1,2,3])
print("Numpy array multiplication: ", ny_array * 3)

Numpy array multiplication:  [3 6 9]


In [ ]:
# Rank 0 (Scalar)

a = np.array(10)
a.ndim

0

In [ ]:
# Rank 1 (Vector)

a = np.array([1,2,3,4,5])
a.ndim

1

In [ ]:
# Rank 2 (Matrix)

a = np.array([
    [1,2,3],
    [5,6,7]
])
a.ndim

2

Classwork

* Create the 5x5 matrix and see the rank.

In [ ]:
x = np.array([
    [1,2,3,4,5],
    [1,3,5,7,9],
    [2,3,5,7,11],
    [2,4,6,8,10],
    [5,10,15,20,25]
])

In [ ]:
print("The shape of matrix is: ", x.shape)
print("The n-dimension of matrix is: ", x.ndim)
print("The rank of matrix is: ", np.linalg.matrix_rank(x))

The shape of matrix is:  (5, 5)
The n-dimension of matrix is:  2
The rank of matrix is:  3


In [ ]:
zeroes = np.zeros((5,5))
print(zeroes)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
ones = np.ones((5,5))
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
ones = np.ones((5,5), dtype="int8")
print(ones)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
np.ones(shape=(4,5), dtype="int8")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [ ]:
a = np.array([
    [1,2,3],
    [5,6,7]
])
print(a.sum(axis=0))

[ 6  8 10]


In [ ]:
print(a.sum(axis=1))

[ 6 18]


In [ ]:
#Random array

ran = np.random.random((3,3))
print(ran)

[[0.83656331 0.42664845 0.21869415]
 [0.12868115 0.65618852 0.99186265]
 [0.4799153  0.22941312 0.18117322]]


In [ ]:
#full
full = np.full((5,2,5), 9)
full

array([[[9, 9, 9, 9, 9],
        [9, 9, 9, 9, 9]],

       [[9, 9, 9, 9, 9],
        [9, 9, 9, 9, 9]],

       [[9, 9, 9, 9, 9],
        [9, 9, 9, 9, 9]],

       [[9, 9, 9, 9, 9],
        [9, 9, 9, 9, 9]],

       [[9, 9, 9, 9, 9],
        [9, 9, 9, 9, 9]]])

In [ ]:
#linespace() - create evenly spaced value

arr = np.linspace(0,100,20)
arr

array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
        21.05263158,  26.31578947,  31.57894737,  36.84210526,
        42.10526316,  47.36842105,  52.63157895,  57.89473684,
        63.15789474,  68.42105263,  73.68421053,  78.94736842,
        84.21052632,  89.47368421,  94.73684211, 100.        ])

In [ ]:
#diag() - create diagnol matrix

arr = np.diag([1,2,3,4,5])
arr

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [ ]:
#eye() - create matrix with ones on diagnol

arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
arr = np.eye(3,4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
#identity() - create identity matrix (always square matrix)

arr = np.identity(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#Create array of random numbers

arr = np.random.rand(2,3)
arr

array([[0.58658141, 0.23820804, 0.77751576],
       [0.22932963, 0.87777563, 0.26137567]])

In [ ]:
#arange()

arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [ ]:
arr = np.arange(3,8)    # 3 = start and 8 = stop
arr

array([3, 5, 7])

In [ ]:
arr = np.arange(3,15,3)    # start, stop, step
arr

array([ 3,  6,  9, 12])

Create a NumPy array of shape (3, 4) filled entirely with zeros.

In [ ]:
zero_array = np.zeros((3,4))
print(zero_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Using NumPy's arange() function, create an array containing odd numbers from 1 to 19.

In [ ]:
odd_array = np.arange(1,20,2)
print(odd_array)

[ 1  3  5  7  9 11 13 15 17 19]


Using NumPy's linspace() function, create an array of 5 evenly spaced values
between 0 and 100.

In [ ]:
spaced_array = np.linspace(0,100,5)
print(spaced_array)

[  0.  25.  50.  75. 100.]


Use the numpy add function to add the values 34 and 29 in the cell below.

In [ ]:
import numpy as np

result = np.add(34, 29)
print(result)

63


Declare a new array with contents [5,4,3,2,1] and slice it to select the last 3 items.

In [ ]:
arr = np.array([5,4,3,2,1])
last_three = arr[-3:]
print(last_three)

[3 2 1]


Select all the elements in the array below excluding the last one.

In [ ]:
result = arr[:-1]
print(result)

[5 4 3 2]


Use arr as defined in 2,3. Exclude the last element from the list, but now only select every 3rd element. Remember the third index indicates stride.

In [ ]:
result = arr[:-1:3]
print(result)

[5 2]


You’ll need to combine array comparisons and logical operators to solve this one. Find out the values in the following array that are greater than 3 AND less than 7.
The output should be a boolean array.

In [ ]:
arr = np.array([1,2,5,6,7,9])
result = (arr > 3) & (arr < 7)
print(arr[result])

[5 6]
