<a href="https://colab.research.google.com/github/mhrznamrit/dsml_batch_12/blob/main/Day28_NumPy_Matrix_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
matrix1 = np.array([
    [1,2],
    [5,4]
])
matrix1

array([[1, 2],
       [5, 4]])

In [ ]:
matrix2 = np.array([
    [3,4],
    [2,6]
])
matrix2

array([[3, 4],
       [2, 6]])

In [ ]:
mat_add = matrix1 + matrix2
mat_add

array([[ 4,  6],
       [ 7, 10]])

In [ ]:
mat_sub = matrix1 - matrix2
mat_sub

array([[-2, -2],
       [ 3, -2]])

In [ ]:
mat_mul = matrix1 * matrix2       # WRONG CONCEPT
mat_mul

array([[ 3,  8],
       [10, 24]])

In [ ]:
mat_mux = matrix1 @ matrix2
mat_mux

array([[ 7, 16],
       [23, 44]])

In [ ]:
matrix_mx = np.matmul(matrix1, matrix2)
matrix_mx

array([[ 7, 16],
       [23, 44]])

In [ ]:
mat_div = matrix1 / matrix2
mat_div

array([[0.33333333, 0.5       ],
       [2.5       , 0.66666667]])

In [ ]:
print(matrix1)
print("////////")
scalar = 2
result_add = matrix1 + scalar
print(result_add)

[[1 2]
 [5 4]]
////////
[[3 4]
 [7 6]]


In [ ]:
print(matrix2)
print("////////")
scalar = 3
result_mux = matrix2 * scalar
print(result_mux)

[[3 4]
 [2 6]]
////////
[[ 9 12]
 [ 6 18]]


In [ ]:
matrix3 = np.array([
    [1,2,3],
    [4,5,6]
])
array1 = np.array([7,8,9])
result = matrix3 + array1
result

array([[ 8, 10, 12],
       [11, 13, 15]])

In [ ]:
A = np.array([
    [1,3],
    [2,4]
])
det = np.linalg.det(A)
print(det)

-2.0


In [ ]:
A_inv = np.linalg.inv(A)
print(A_inv)

[[-2.   1.5]
 [ 1.  -0.5]]


In [ ]:
mul = np.matmul(A,A_inv)
print(mul)

[[1. 0.]
 [0. 1.]]


In [ ]:
a = np.array([
    [2,1],
    [1,3]
])
b = np.array([5,6])
x = np.linalg.solve(a,b)
x

array([1.8, 1.4])

In [ ]:
# x+y+z=6
# 2x+5y+z=-4
# 2x+3y+8z=5

p = np.array([
    [1,1,1],
    [2,5,1],
    [2,3,8]
])
q = np.array([6,-4,5])
y = np.linalg.solve(p,q)
y

array([11.68421053, -5.42105263, -0.26315789])

In [ ]:
x = np.array([
  [1,1],
  [2,1],
  [3,1]
])

y = np.array([2,3,5])

x_t = x.T

mul = x_t @ x

res_inv = np.linalg.inv(mul)

res1 = res_inv @ x_t

final = res1 @ y

final

array([1.5       , 0.33333333])

In [ ]:
beta = np.linalg.inv(x.T @ x) @ x.T @ y

array([1.5       , 0.33333333])

In [ ]:
print("Slope (m): ", beta[0])
print("Intercept (c): ", beta[1])

Slope (m):  1.499999999999999
Intercept (c):  0.3333333333333348


# Practice Questions

Create two 3×3 matrices and perform matrix addition.

In [ ]:
mat1 = np.array([
    [1,7,0],
    [9,3,8],
    [2,4,5]
])
mat2 = np.array([
    [12,-2,7],
    [0,17,2],
    [-10,6,11]
])
mat_add = mat1 + mat2
mat_add

array([[13,  5,  7],
       [ 9, 20, 10],
       [-8, 10, 16]])

Find the transpose of a 2×4 matrix.

In [ ]:
mat3 = np.array([
    [1,5,7,9],
    [2,8,0,3]
])
transpose_mat3 = mat3.T
transpose_mat3

array([[1, 2],
       [5, 8],
       [7, 0],
       [9, 3]])

Calculate the determinant of a 2×2 matrix.

In [ ]:
mat4 = np.array([
    [7,-5],
    [3,9]
])
det = np.linalg.det(mat4)
print("Determinant : ", det)

Determinant :  78.0


Find the inverse of a matrix and verify the result.

In [ ]:
inv_mat4 = np.linalg.inv(mat4)
print("Given matrix:\n", mat4)
print("Inverse matrix:\n", inv_mat4)
verification = np.matmul(mat4, inv_mat4)
print("Verification:\n", np.round(verification))

Given matrix:
 [[ 7 -5]
 [ 3  9]]
Inverse matrix:
 [[ 0.11538462  0.06410256]
 [-0.03846154  0.08974359]]
Verification:
 [[ 1. -0.]
 [ 0.  1.]]


Create a 4×4 identity matrix.

In [ ]:
identity_mat = np.eye(4)
print(identity_mat)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Find the rank of a given matrix.

In [ ]:
mat5 = np.array([
    [1,7,5],
    [20,-3,12],
    [13,0,17],
    [0,23,10]
])
rank = np.linalg.matrix_rank(mat5)
print("Rank of the matrix: ", rank)

Rank of the matrix:  3


Compute the trace of a matrix.

In [ ]:
mat6 = np.array([
    [1,7,0],
    [9,3,8],
    [2,4,5]
])
trace_val = np.trace(mat6)
print("Given matrix:\n", mat6)
print("Trace of the matrix: ", trace_val)

Given matrix:
 [[1 7 0]
 [9 3 8]
 [2 4 5]]
Trace of the matrix:  9


Find eigenvalues and eigenvectors of a 2×2 matrix.

In [ ]:
new_mat = np.array([
    [1,5],
    [0,7]
])
eigenvalues, eigenvectors = np.linalg.eig(new_mat)
print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues:
 [1. 7.]
Eigenvectors:
 [[1.         0.6401844 ]
 [0.         0.76822128]]


Solve a system of linear equations using np.linalg.solve().
$$\begin{aligned} 2x + y &= 5 \\ x + 3y &= 6 \end{aligned}$$

In [ ]:
A = np.array([
    [2,1],
    [1,3]
])
B = np.array([5,6])
x = np.linalg.solve(A,B)
print("x = ", x[0])
print("y = ", x[1])

x =  1.8
y =  1.4


Perform SVD on a 3×3 matrix and print U, S, and VT.

In [ ]:
my_matrix = np.array([
    [7,0,-3],
    [1,3,8],
    [-6,5,2]
])
U, S, VT = np.linalg.svd(my_matrix)
print("U Matrix:\n", U)
print("Singular values (S):\n", S)
print("VT (V Transposed) Matrix:\n", VT)

U Matrix:
 [[-0.57691207 -0.4024962   0.71075261]
 [ 0.4948466  -0.864522   -0.08791222]
 [ 0.6498456   0.30099589  0.69792705]]
Singular values (S):
 [11.25388569  7.57503686  3.60123221]
VT (V Transposed) Matrix:
 [[-0.66133705  0.42063407  0.62104773]
 [-0.72448106 -0.1437071  -0.67414796]
 [ 0.19432064  0.89577634 -0.39978025]]


Calculate the norm of a vector.

In [ ]:
v = np.array([3,4])
norm = np.linalg.norm(v)
print("Vector: ", v)
print("Norm: ", norm)

Vector:  [3 4]
Norm:  5.0


Find the dot product of two vectors.

In [ ]:
vect1 = np.array([1,2,3])
vect2 = np.array([4,5,6])
dot_product = np.dot(vect1, vect2)
print("Vector 1: ", vect1)
print("Vector 2: ", vect2)
print("Dot product:", dot_product)

Vector 1:  [1 2 3]
Vector 2:  [4 5 6]
Dot product: 32


Find the cross product of two 3D vectors.

In [ ]:
p = np.array([2,3,1])
q = np.array([4,1,2])
cross_product = np.cross(p,q)
print("Vector 1: ", p)
print("Vector 2: ", q)
print("Cross product:", cross_product)

Vector 1:  [2 3 1]
Vector 2:  [4 1 2]
Cross product: [  5   0 -10]


Multiply two matrices using @.

In [ ]:
matrix1 = np.array([
    [1,2,7],
    [5,4,8]
])
matrix2 = np.array([
    [3,0],
    [8,6],
    [1,9]
])
matrix_mul = matrix1 @ matrix2
print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)
print("Matrix multiplication:\n", matrix_mul)

Matrix 1:
 [[1 2 7]
 [5 4 8]]
Matrix 2:
 [[3 0]
 [8 6]
 [1 9]]
Matrix multiplication:
 [[26 75]
 [55 96]]


Verify that A @ np.linalg.inv(A) produces an identity matrix.

In [ ]:
A = np.array([
  [4,7],
  [2,6]
])
A_inv = np.linalg.inv(A)
identity_matrix = A @ A_inv
print("Given matrix:\n", A)
print("Inverse matrix:\n", A_inv)
print("Verification:\n", np.round(identity_matrix))

Given matrix:
 [[4 7]
 [2 6]]
Inverse matrix:
 [[ 0.6 -0.7]
 [-0.2  0.4]]
Verification:
 [[ 1. -0.]
 [ 0.  1.]]
